# -*- coding: utf-8 -*-
"""Projeto Variáveis Macroeconômicas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wbsYOO5zYM1Xnbpu8ZZeuH1rDfFXaJoD

# ***Variáveis Macroeconômicas***

*   Preços de Alimentos
*   Salário e Renda
---

# **Apresentação**

No presente projeto abordaremos variáveis macroeconômicas que influênciam diretamente a vida diária dos cidadãos, principalmete do estado de São Paulo, que será o estado que estaremos analisando a base de dados.

Focaremos nos anos de 1990 a 2000 onde analisaremos os dados de cada variável individualmente e também os dados num todo.

Abordaremos o valor médio mensalmente no atacado do arroz longo fino agulinha, o valor médio mensalmente no atacado do óleo de soja refinado e por fim o valor do salário mínimo real no nosso país também numa visão mensal, além de que levaremos em consideracão a inflação que ocorreu entre 1990 a 1999 e os acréscimos ou decrécimos que ocorreram no valor do arroz longo fino agulinha, no valor do óleo de soja refinado e no valor do salário mínimo real.

# **Motivação**

Criei três perguntas motivadores para guiar meu projeto:

- Pergunta motivadora para a análise variável 1 X variável 2

Como a inflação de 1990 a 1999 influenciou o valor do Arroz – Longo Fino Agulinha e no valor do Óleo de Soja – Refinado?

- Pergunta motivadora para a análise variável 2 X variável 3

Relação entre o acréscimo/decréscimo no valor do Salário Mínimo Real e no valor do Óleo de Soja – Refinado. Foram diretamente ou inversamente proporcionais? Os valores que acresceram/decresceram, comparando e analisando ambas variáveis simultaneamente, foram muito diferentes, ou seja, ficaram muitos dispersos?

- Pergunta motivadora para a análise variável 1 X variável 3

Relação entre o acréscimo/decréscimo no valor do Salário Mínimo Real e no valor do Arroz – Longo Fino Agulinha. Foram diretamente ou inversamente proporcionais? Os valores que acresceram/decresceram, comparando e analisando ambas variáveis simultaneamente, foram muito diferentes, ou seja, ficaram muitos dispersos?

---

Mas o que mais me engajou e me incentivou a escolher tais variáveis foi pensar na justiça nos valores das três variávies; será que o salário mínimo real acompanhou os acréscimos ou decrécimos nos valores dos alimentos, para ser algo justo para todos, princilpamnete para o cidadão do estado de São Paulo?

Então vamos descobrir analisando nossos dados:

# **Fontes dos Dados**

- ### **Preço médio no atacado: arroz longo fino agulhinha (30 kg - SP)**

**Frequência:** Mensal de 1990.01 até 2000.12

**Fonte:** Companhia Nacional de Abastecimento, Indicadores Econômicos (Conab/IE)

**Unidade:** R$

**Comentário:** Preço médio - atacado - arroz - longo fino agulhinha - 30 kg - SP. Obs.: Preço médio mensal no atacado praticado no estado de São Paulo. Série descontinuada pela fonte.

**Atualizado em:** 11/10/2018

- ### **Preço médio no atacado: óleo de soja refinado (20 latas - SP)**

**Frequência:** Mensal de 1990.01 até 2000.12

**Fonte:** Companhia Nacional de Abastecimento, Indicadores Econômicos (Conab/IE)

**Unidade:** R$

**Comentário:** Série descontinuada pela fonte.

**Atualizado em:** 19/08/2003

- ### **Salário mínimo real**

**Frequência:** Mensal de 1990.01 até 2000.12

**Fonte:** Instituto de Pesquisa Econômica Aplicada

**Unidade:** R$ (do último mês)

**Comentário:** O Salário mínimo nominal é o menor salário definido por lei para remuneração do trabalhador brasileiro. O salário minimo real é o valor do salário mínimo nominal abatido o percentual de inflação do mês, o qual é medido através de diferentes índices de preço. O salário mínimo urbano foi instituído no Brasil por decreto-lei do presidente Getúlio Vargas, durante a ditadura do Estado Novo, e começou a vigorar em julho de 1940, com valores diferenciados entre estados e sub-regiões. Em 1943, foi incorporado à Consolidação das Leis do Trabalho (CLT) e, em 1963, foi estendido ao campo por meio do Estatuto do Trabalhador Rural. Foi nacionalmente unificado em maio de 1984, mas, desde 2000, a Lei Complementar 103 permite que os estados fixem pisos estaduais superiores ao mínimo nacional. Os dados desta série para o período em que a legislação federal definia faixas diversificadas referem-se sempre ao maior salário mínimo vigente no país.

**Atualizado em:** 06/11/2020

# **Importando Bibliotecas**
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline

"""# **Variável 1**

Preço médio - atacado - arroz - longo fino agulhinha - 30 kg - SP - R$ - Companhia Nacional de Abastecimento, Indicadores Econômicos (Conab/IE) - DEPAE12_ATARAG12

- **Filtrando Dados**
"""

dfGeral = pd.read_csv("/content/ipeadata[23-11-2020-04-13].csv", sep = "\t")
df1 = dfGeral[["Data", "Preço médio - atacado - arroz - longo fino agulhinha - 30 kg - SP - R$"]]
df1

"""- **Estatística Descritiva**"""

df1a = dfGeral[["Preço médio - atacado - arroz - longo fino agulhinha - 30 kg - SP - R$"]]
df1a.describe()

a = df1['Preço médio - atacado - arroz - longo fino agulhinha - 30 kg - SP - R$'].median()
b = df1['Preço médio - atacado - arroz - longo fino agulhinha - 30 kg - SP - R$'].mode()
c = df1["Preço médio - atacado - arroz - longo fino agulhinha - 30 kg - SP - R$"].max()-df1["Preço médio - atacado - arroz - longo fino agulhinha - 30 kg - SP - R$"].min()
d = df1['Preço médio - atacado - arroz - longo fino agulhinha - 30 kg - SP - R$'].var()
print("Mediana =", a, "\n")
print('Amplitude =', c, "\n")
print('Variância =', d, "\n")
print('Moda =', b, "\n")

"""- **Gráfico de Histograma**"""

df1.hist(column = "Preço médio - atacado - arroz - longo fino agulhinha - 30 kg - SP - R$")

"""- **Gráfico de Boxplot**"""

df1.boxplot(column = "Preço médio - atacado - arroz - longo fino agulhinha - 30 kg - SP - R$")

"""# **Variável 2**

Preço médio - atacado - óleo de soja - refinado - 20 latas - SP - R$ - Companhia Nacional de Abastecimento, Indicadores Econômicos (Conab/IE) - DEPAE12_ATOL12

- **Filtrando Dados**
"""

dfGeral = pd.read_csv("/content/ipeadata[23-11-2020-04-13].csv", sep = "\t")
df2 = dfGeral[["Data", "Preço médio - atacado - óleo de soja - refinado - 20 latas - SP - R$"]]
df2

"""- **Estatística Descritiva**

"""

df2a = dfGeral[["Preço médio - atacado - óleo de soja - refinado - 20 latas - SP - R$"]]
df2a.describe()

a = df2["Preço médio - atacado - óleo de soja - refinado - 20 latas - SP - R$"].median()
b = df2["Preço médio - atacado - óleo de soja - refinado - 20 latas - SP - R$"].mode()
c = df2["Preço médio - atacado - óleo de soja - refinado - 20 latas - SP - R$"].max()-df2["Preço médio - atacado - óleo de soja - refinado - 20 latas - SP - R$"].min()
d = df2["Preço médio - atacado - óleo de soja - refinado - 20 latas - SP - R$"].var()
print("Mediana =", a, "\n")
print('Amplitude =', c, "\n")
print('Variância =', d, "\n")
print('Moda =', b, "\n")

"""- **Gráfico de Histograma**"""

df2.hist(column = "Preço médio - atacado - óleo de soja - refinado - 20 latas - SP - R$")

"""- **Gráfico de Boxplot**"""

df2.boxplot(column = "Preço médio - atacado - óleo de soja - refinado - 20 latas - SP - R$")

"""# **Variável 3**

Salário mínimo real - R$ (do último mês) - Instituto de Pesquisa Econômica Aplicada - GAC12_SALMINRE12

- **Filtrando Dados**
"""

dfGeral = pd.read_csv("/content/ipeadata[23-11-2020-04-13].csv", sep = "\t")
df3 = dfGeral[["Data", "Salário mínimo real - R$"]]
df3

"""- **Estatística Descritiva**"""

df3a = dfGeral[["Salário mínimo real - R$"]]
df3a.describe()

a = df3["Salário mínimo real - R$"].median()
b = df3["Salário mínimo real - R$"].mode()
c = df3["Salário mínimo real - R$"].max()-df3["Salário mínimo real - R$"].min()
d = df3["Salário mínimo real - R$"].var()
print("Mediana =", a, "\n")
print('Amplitude =', c, "\n")
print('Variância =', d, "\n")
print('Moda =', b, "\n")

"""- **Gráfico de Histograma**"""

df3.hist(column = "Salário mínimo real - R$")

"""- **Gráfico de Boxplot**"""

df3.boxplot(column = "Salário mínimo real - R$")

"""# **Agora que já analisamos nossas variávies individualmente, vamos analisa-las em conjunto para alguns aspectos:**

"""

dfGeral = pd.read_csv("/content/ipeadata[23-11-2020-04-13].csv", sep = "\t")
dfGeral

"""- **Matriz de Correlação Geral**"""

dfGeral.corr()

"""# **Variável 1 X Variável 2**

- **Matriz de Correlação**
"""

corr1 = dfGeral['Preço médio - atacado - arroz - longo fino agulhinha - 30 kg - SP - R$'].corr(dfGeral['Preço médio - atacado - óleo de soja - refinado - 20 latas - SP - R$'])
print("A correlação entre o Preço médio no atacado do arroz longo fino agulhinha e o Preço médio no atacado do óleo de soja refinado é de", corr1)

if 1 >= abs(corr1) >= 0.9:
  print("A correlação entre o Preço médio no atacado do arroz longo fino agulhinha e o Preço médio no atacado do óleo de soja refinado é muito forte")
elif 0.9 > abs(corr1) >= 0.7:
  print("A correlação entre o Preço médio no atacado do arroz longo fino agulhinha e o Preço médio no atacado do óleo de soja refinado é forte")
elif 0.7 > abs(corr1) >= 0.4:
  print("A correlação entre o Preço médio no atacado do arroz longo fino agulhinha e o Preço médio no atacado do óleo de soja refinado é moderada")
elif 0.4 > abs(corr1) >= 0.2:
  print("A correlação entre o Preço médio no atacado do arroz longo fino agulhinha e o Preço médio no atacado do óleo de soja refinado é fraca")
elif 0.2 > abs(corr1) >= 0:
  print("A correlação entre o Preço médio no atacado do arroz longo fino agulhinha e o Preço médio no atacado do óleo de soja refinado é muito fraca")

"""- **Regressão Linear**"""

# Preço médio - atacado - arroz - longo fino agulhinha - 30 kg - SP - R$(Variável Independente) e Preço médio - atacado - óleo de soja - refinado - 20 latas - SP - R$(Variável Dependente)

r1 = corr1**2
print("R² =", r1, "\n")

(a,b) = np.polyfit(x=dfGeral['Preço médio - atacado - arroz - longo fino agulhinha - 30 kg - SP - R$'], y= dfGeral['Preço médio - atacado - óleo de soja - refinado - 20 latas - SP - R$'], deg=1)
modelo = a*dfGeral['Preço médio - atacado - arroz - longo fino agulhinha - 30 kg - SP - R$']+ b
print(modelo)

dfGeral.plot(x = 'Preço médio - atacado - arroz - longo fino agulhinha - 30 kg - SP - R$', y = 'Preço médio - atacado - óleo de soja - refinado - 20 latas - SP - R$', kind = 'scatter')

"""# **Variável 2 X Variável 3**

- **Matriz de Correlação**
"""

corr2 = dfGeral['Salário mínimo real - R$'].corr(dfGeral['Preço médio - atacado - óleo de soja - refinado - 20 latas - SP - R$'])
print("A correlação entre o Preço médio no atacado do óleo de soja refinado e o valor Salário mínimo real é de", corr2)

if 1 >= abs(corr2) >= 0.9:
  print("A correlação entre o Preço médio no atacado do óleo de soja refinado e o valor Salário mínimo real é muito forte")
elif 0.9 > abs(corr2) >= 0.7:
  print("A correlação entre o Preço médio no atacado do óleo de soja refinado e o valor Salário mínimo real é forte")
elif 0.7 > abs(corr2) >= 0.4:
  print("A correlação entre o Preço médio no atacado do óleo de soja refinado e o valor Salário mínimo real é moderada")
elif 0.4 > abs(corr2) >= 0.2:
  print("A correlação entre o Preço médio no atacado do óleo de soja refinado e o valor Salário mínimo real é fraca")
elif 0.2 > abs(corr2) >= 0:
  print("A correlação entre o Preço médio no atacado do óleo de soja refinado e o valor Salário mínimo real é muito fraca")

"""- **Regressão Linear**"""

# Preço médio - atacado - óleo de soja - refinado - 20 latas - SP - R$(Variável Independente) e Salário mínimo real - R$(Variável Dependente)

r2 = corr2**2
print("R² =", r2, "\n")

(a,b) = np.polyfit(x=dfGeral['Preço médio - atacado - óleo de soja - refinado - 20 latas - SP - R$'], y= dfGeral['Salário mínimo real - R$'], deg=1)
modelo = a*dfGeral['Preço médio - atacado - óleo de soja - refinado - 20 latas - SP - R$']+ b
print(modelo)

dfGeral.plot(x = 'Preço médio - atacado - óleo de soja - refinado - 20 latas - SP - R$', y = 'Salário mínimo real - R$', kind = 'scatter')

"""# **Variável 1 X Variável 3**

- **Matriz de Correlação**
"""

corr3 = dfGeral['Salário mínimo real - R$'].corr(dfGeral['Preço médio - atacado - arroz - longo fino agulhinha - 30 kg - SP - R$'])
print("A correlação entre o Preço médio no atacado do arroz longo fino agulhinha e o valor Salário mínimo real é de", corr3)

if 1 >= abs(corr3) >= 0.9:
  print("A correlação entre o Preço médio no atacado do arroz longo fino agulhinha e o valor Salário mínimo real é muito forte")
elif 0.9 > abs(corr3) >= 0.7:
  print("A correlação entre o Preço médio no atacado do arroz longo fino agulhinha e o valor Salário mínimo real é forte")
elif 0.7 > abs(corr3) >= 0.4:
  print("A correlação entre o Preço médio no atacado do arroz longo fino agulhinha e o valor Salário mínimo real é moderada")
elif 0.4 > abs(corr3) >= 0.2:
  print("A correlação entre o Preço médio no atacado do arroz longo fino agulhinha e o valor Salário mínimo real é fraca")
elif 0.2 > abs(corr3) >= 0:
  print("A correlação entre o Preço médio no atacado do arroz longo fino agulhinha e o valor Salário mínimo real é muito fraca")

"""- **Regressão Linear**

"""

# Preço médio - atacado - arroz - longo fino agulhinha - 30 kg - SP - R$(Variável Independente) e Salário mínimo real - R$(Variável Dependente)

r3 = corr3**2
print("R² =", r3, "\n")

(a,b) = np.polyfit(x=dfGeral['Preço médio - atacado - arroz - longo fino agulhinha - 30 kg - SP - R$'], y= dfGeral['Salário mínimo real - R$'], deg=1)
modelo = a*dfGeral['Preço médio - atacado - arroz - longo fino agulhinha - 30 kg - SP - R$']+ b
print(modelo)

dfGeral.plot(x = 'Preço médio - atacado - arroz - longo fino agulhinha - 30 kg - SP - R$', y = 'Salário mínimo real - R$', kind = 'scatter')

"""# **Resultados e Conclusão**

Observando nossas várias análises referente a base de dados abordada, percebemos nitidamente que as três variáveis não acompanham um ritmo uniforme entre elas.

Podemos captar também que por mais que o valor do Arroz Longo Fino Agulinha e do Óleo de Soja Refinado apenas crescem com o passar do tempo, o valor do Salário Mínimo Real, por outro lado, oscila muito crescendo e descrecendo com o passar dos meses, sendo que caiu bem mais o valor do que subiu, o que influência diretamente no dia a dia do cidadão do estado de São Paulo.

Por exemplo, no primeiro mês que analisamos (01/1990) o valor do Arroz Longo Fino Agulinha e do Óleo de Soja Refinado, ambos no atacado, estavam por volta de RS 0.0001 e o valor do Salário Mínimo Real por volta RS 600.36, já no ultimo mês que analisamos (12/2000) o valor do Arroz Longo Fino Agulinha estava aproximadamente RS 20.69, do Óleo de Soja Refinado estava aproximadamente RS 18.25, ambos no atacado e do Salário Mínimo Real aproximadamente RS 506.61.

Logo percebemos, que enquanto a porcentagem de decrescimo no valor do Sálario Mínimo Real é bem maior que a porcentagem de acrescimo, o valor do Arroz Longo Fino Agulinha e do Óleo de Soja Refinado apenas aumentaram, o que vem acontecendo infelizmente até hoje, dificultando muito a vida dos cidadões.

O período de inflação no Brasil (1990 a 1999) influênciou diretamente esses valores e deixa cequelas até hoje. Nesse período o valor do Sálario Mínimo Real, caiu cerca de 20% (fazendo a análise a partir do primeiro e do último mês desse intervalo) enquanto o valor do Arroz Longo Fino Agulinha e do Óleo de Soja Refinado aumentaram mais de 100% (fazendo a análise a partir do primeiro e do último mês desse intervalo).

Agora podemos responder nossas perguntas motivadoras. A inflação influenciou sim e muito nos valores de forma muito radical e por mais que depois do período de inflação o valor do Arroz Longo Fino Agulinha e do Óleo de Soja Refinado diminuiram limitadamente e o valor do Salario Mínimo Real aumentou limitadamente, as variáveis (variáveis 1 e 2 X variável 3) continuam sendo inversamente proporcionais e exatamente por esse motivo, analisando nossa Matriz de Correlação entre as variáveis 1 e 2 foi 0.98, o que é uma correlação muito forte e positiva, pois o par cresce junto; já a Matriz de Correlação entre as variáveis 2 e 3 e as variáveis 1 e 3 resultaram em -0.11 e -0.05, respectivamente, o que são correlações muito fracas e negativas, pois a variável dependente decresce conforme a variável independente cresce, além de serem valores muito dispersos, como já concluimos mais acima.

E como foi dito na motivação, o que mais me engajou e me incentivou a escolher tais variáveis foi pensar na justiça nos valores das três variávies; será que o salário mínimo real acompanhou os acréscimos ou decrécimos nos valores dos alimentos, para ser algo justo para todos, principalmente para o cidadão do estado de São Paulo? E vemos nitidamente que nossa resposta é NÃO. Não há justiça nos valores infelizmente desde muito tempo no Brasil, como observamos analisando São Paulo que é a maior metrópole do país, e esse problema vem perpetuando até os dias atuais sem cessar.

---

Um ótimo projeto, onde aumentou meu olhar crítico e meu conhecimento tanto na área de Macroeconômia quanto na área da Ciência da Computação. Foi muito vantajoso desenvolver tal projeto e a satisfação é imensa.

# **Bibliografias**

- http://www.ipeadata.gov.br/Default.aspx

- Notebooks em Python - Turma DC8BIS0005-15SA (Profa Ana Simões)

- https://docs.google.com/spreadsheets/d/1XWKCE7WSNqJiFAIwZUgypZ_ggr8d5DyglNBfv7DjZxk/edit?usp=sharing (DataFrame utilizado com as bases de dados)
"""